# Generated by Django 3.2.7 on 2021-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('model', models.TextField(verbose_name='Modelo')),
                ('price', models.TextField(verbose_name='Precio')),
            ],
            options={
                'verbose_name_plural': 'SmartPhones',
            },
        ),
    ]
